packages:
  - tooling/*
  - packages/*
  - apps/*

autoInstallPeers: true

catalog:
  '@types/node': 25.6.0
  typescript: 5.9.3

linkWorkspacePackages: false

onlyBuiltDependencies:
  - core-js-pure
  - esbuild

overrides:
  node-fetch: npm:node-fetch-native@latest

preferWorkspacePackages: true

savePrefix: ''

saveWorkspaceProtocol: rolling

shamefullyHoist: true
