packages:
  - tooling/*
  - packages/*
  - apps/*

autoInstallPeers: true

catalog:
  '@types/node': 24.10.9
  typescript: 6.0.2

linkWorkspacePackages: false

onlyBuiltDependencies:
  - core-js-pure
  - esbuild

overrides:
  node-fetch: npm:node-fetch-native@latest

preferWorkspacePackages: true

savePrefix: ''

saveWorkspaceProtocol: rolling

shamefullyHoist: true
